# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text='Sender Name', max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('sender_contact', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sender_address1', models.CharField(blank=True, max_length=100)),
                ('sender_address2', models.CharField(blank=True, max_length=100)),
                ('sender_address3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
