# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
