# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_member_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text='Sender Name', max_length=100)),
                ('address1', models.CharField(help_text='Sender Address  metropolitan city / state', max_length=100)),
                ('address2', models.CharField(help_text='Sender Address  city / street', max_length=100)),
                ('address3', models.CharField(help_text='Sender Address  extra address', max_length=100)),
                ('sender_contact', models.CharField(blank=True, help_text='Sender information for Contact', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Letter Title', max_length=100)),
                ('content', models.TextField(help_text='Letter Content')),
                ('receiver_address1', models.CharField(help_text='Receiver Address  metropolitan city / state', max_length=100)),
                ('receiver_address2', models.CharField(blank=True, help_text='Receiver Address  city / street', max_length=100)),
                ('receiver_address3', models.CharField(blank=True, help_text='Receiver Address  extra address', max_length=100)),
            ],
        ),
    ]
