# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_auto_20160211_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='receiver_address1',
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
