# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import letter.models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_letter_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='100\uc790 \uc774\ub0b4\ub85c \uc785\ub825\ud558\uc138\uc694', max_length=100, validators=[letter.models.min_length_validator])),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', letter.models.PhoneField(blank=True, max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
