# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='jaemok',
        ),
    ]
