# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0010_auto_20160211_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='jaemok',
            new_name='title',
        ),
    ]
