# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_auto_20160211_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-02-12 00:00:00'),
            preserve_default=False,
        ),
    ]
